# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-19 06:10
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
