# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_auto_20250219_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': '\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0430', 'verbose_name_plural': '\u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': '\u043f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a', 'verbose_name_plural': '\u043f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'\xd0\xb4\xd0\xb0\xd1\x82\xd0\xb0 \xd1\x81\xd0\xbe\xd0\xb7\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=tinymce.models.HTMLField(verbose_name=b'\xd1\x81\xd0\xbe\xd0\xbe\xd0\xb1\xd1\x89\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(max_length=100, verbose_name=b'\xd1\x82\xd0\xb5\xd0\xbc\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='birthday',
            field=models.DateField(verbose_name=b'\xd0\xb4\xd0\xb5\xd0\xbd\xd1\x8c \xd1\x80\xd0\xbe\xd0\xb6\xd0\xb4\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name=b'\xd1\x8d\xd0\xbb\xd0\xb5\xd0\xba\xd1\x82\xd1\x80\xd0\xbe\xd0\xbd\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbe\xd1\x87\xd1\x82\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name=b'\xd0\xb8\xd0\xbc\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name=b'\xd1\x84\xd0\xb0\xd0\xbc\xd0\xb8\xd0\xbb\xd0\xb8\xd1\x8f'),
        ),
    ]
