# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_auto_20250220_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='reached_subs',
            field=models.IntegerField(default=0, verbose_name=b'\xd0\xba\xd0\xbe\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe \xd0\xbf\xd0\xbe\xd0\xbb\xd1\x83\xd1\x87\xd0\xb8\xd0\xb2\xd1\x88\xd0\xb8\xd1\x85 \xd1\x80\xd0\xb0\xd1\x81\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd1\x83'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='read',
            field=models.ManyToManyField(to='sender.Subscriber', verbose_name=b'\xd0\xbf\xd1\x80\xd0\xbe\xd1\x87\xd0\xb8\xd1\x82\xd0\xb0\xd0\xb2\xd1\x88\xd0\xb8\xd0\xb5 \xd0\xbf\xd0\xbe\xd0\xb4\xd0\xbf\xd0\xb8\xd1\x81\xd1\x87\xd0\xb8\xd0\xba\xd0\xb8'),
        ),
    ]
