# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-20 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_auto_20250220_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='read',
            new_name='read_subs',
        ),
    ]
